AllCops:
  TargetRubyVersion: 2.6

# FIXME: how to disable it only for rspec-pipeline.rb?
Naming/FileName:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
