pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - bash: echo "Hello world"
  - job: SecurityScan
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    steps:
      - bash: echo "run scan"
        name: RunScan
      - bash: echo "publish result"
        name: Publish
        condition: succeededOrFailed()

- stage: DeployToDev
  dependsOn: Build
  jobs:
  - job: B1
    steps:
    - bash: echo "Hello world"

- stage: DeployToCi
  dependsOn: DeployToDev
  jobs:
  - job: B1
    steps:
    - bash: echo "Hello world"

- stage: DeployToStage
  dependsOn: DeployToCi
  jobs:
  - job: B1
    steps:
    - bash: echo "Hello world"

- stage: DeployToProd
  dependsOn: DeployToStage
  jobs:
  - job: B1
    steps:
    - bash: echo "Hello world"
